import ARGUMENTS from './interface/ARGUMENTS';
declare class ImageViewer {
    constructor(args?: ARGUMENTS);
    private _wrapper;
    private _backdrop;
    private _image;
    private _$actionBar;
    private _$actionBarTitle;
    private _$downloadBar;
    private _$downloadIcon;
    private _$touchStartTarget;
    private _$backArrow;
    private _imageSrc;
    private _widthRatio;
    private _animationDuration;
    private _baseIndex;
    private _actionBarTitle;
    private _gestureScaleRatio;
    private _closeCallback;
    private _movable;
    private _minScaleRation;
    private _maxScaleRation;
    private _isAnimating;
    private _isDefault;
    private _isEnlarge;
    private _id;
    private _windowWidth;
    private _windowHeight;
    private _imageX;
    private _imageY;
    private _imageH;
    private _imageW;
    private _defaultY;
    private _defaultX;
    private _defaultH;
    private _defaultW;
    private _downloadIconText;
    private _openMode;
    private tweenXY(x, y);
    private tweenWH(w, h);
    private tweenXYWH(x, y, w, h, duration);
    private setImageXY(x, y);
    private setImageWH(w, h);
    private setDefaultTouchIndicator();
    private animateXY(x, y);
    private animateXYWH(x, y, w, h);
    private animateDefault();
    private animateMax();
    imageSrc: string;
    movable: boolean;
    private show();
    open(img: HTMLImageElement): void;
    closeCallback: () => void;
    close(): void;
    private _startX;
    private _startY;
    private _imageRatio;
    private _origin;
    private _startT1;
    private _startT2;
    private _touchMoveCount;
    private _touchCount;
    private _moveX;
    private _moveY;
    private _scaleW;
    private _scaleH;
    private _hasTouchStart;
    private _touchStartTime;
    private _startDiagonalLength;
    downloadIconText: string;
    private doubleTouch();
    private _downloadFn;
    downloadFn: () => void;
    private _singleTouch;
    singleTouch: () => void;
    private _longTouch;
    private _longTouchTimer;
    private _longTouchDuration;
    private _longTouchStart;
    private _longTouchTrackX;
    private _longTouchTrackY;
    longTouch: () => void;
    static getDiagonalLength(xl: number, yl: number): number;
    private resetLongTouch();
    touchMove(event: TouchEvent): void;
    private backToProperPlace();
}
export = ImageViewer;
